using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;

// ---- entry point ----
string repoRoot = args.Length > 0 ? args[0] : Directory.GetCurrentDirectory();
string scriptsDir = Path.Combine(repoRoot, "Assets", "Scripts");
string outputPath = Path.Combine(repoRoot, "docs", "codemap.md");

if (!Directory.Exists(scriptsDir))
{
    Console.Error.WriteLine($"Scripts directory not found: {scriptsDir}");
    return 1;
}

// Files generated by InputSystem codegen — include but mark them
var codegenFiles = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
{
    "DownhillControls.cs"
};

var csFiles = Directory.GetFiles(scriptsDir, "*.cs", SearchOption.AllDirectories);

// ---- parse all files ----
var typeInfos = new List<TypeInfo>();

foreach (var filePath in csFiles)
{
    string fileName = Path.GetFileName(filePath);
    string source = File.ReadAllText(filePath);
    var tree = CSharpSyntaxTree.ParseText(source, path: filePath);
    var root = tree.GetCompilationUnitRoot();

    bool isCodegen = codegenFiles.Contains(fileName);

    foreach (var typeDecl in root.DescendantNodes().OfType<BaseTypeDeclarationSyntax>())
    {
        // Only top-level and one level of nesting (skip deeply nested generated types)
        var ancestorTypes = typeDecl.Ancestors().OfType<BaseTypeDeclarationSyntax>().Count();
        if (ancestorTypes > 1) continue;

        string ns = GetNamespace(typeDecl);
        // Strip verbatim identifier prefix (e.g. @DownhillControls -> DownhillControls)
        string name = typeDecl.Identifier.Text.TrimStart('@');
        string kind = typeDecl switch
        {
            ClassDeclarationSyntax c when c.Modifiers.Any(m => m.Text == "static") => "class (static)",
            ClassDeclarationSyntax => "class",
            InterfaceDeclarationSyntax => "interface",
            StructDeclarationSyntax => "struct",
            EnumDeclarationSyntax => "enum",
            RecordDeclarationSyntax r when r.ClassOrStructKeyword.Text == "struct" => "record struct",
            RecordDeclarationSyntax => "record",
            _ => "class"
        };

        var bases = new List<string>();
        if (typeDecl.BaseList != null)
            foreach (var b in typeDecl.BaseList.Types)
                bases.Add(b.Type.ToString());

        var methods = new List<MethodSignature>();
        var fields = new List<FieldRef>();

        if (typeDecl is TypeDeclarationSyntax tds)
        {
            // Public methods
            foreach (var method in tds.Members.OfType<MethodDeclarationSyntax>())
            {
                if (!method.Modifiers.Any(m => m.Text == "public")) continue;
                string retType = method.ReturnType.ToString();
                string paramList = string.Join(", ", method.ParameterList.Parameters
                    .Select(p => $"{p.Type} {p.Identifier}"));
                methods.Add(new MethodSignature(retType, method.Identifier.Text.TrimStart('@'), paramList));
            }

            // Public properties
            foreach (var prop in tds.Members.OfType<PropertyDeclarationSyntax>())
            {
                if (!prop.Modifiers.Any(m => m.Text == "public")) continue;
                fields.Add(new FieldRef(prop.Type.ToString(), prop.Identifier.Text.TrimStart('@'), "property", IsPublic: true));
            }

            // Events (field-like syntax: public event Action Foo)
            foreach (var evDecl in tds.Members.OfType<EventFieldDeclarationSyntax>())
            {
                if (!evDecl.Modifiers.Any(m => m.Text == "public")) continue;
                string evType = evDecl.Declaration.Type.ToString();
                foreach (var v in evDecl.Declaration.Variables)
                    fields.Add(new FieldRef(evType, v.Identifier.Text.TrimStart('@'), "event", IsPublic: true));
            }

            // Fields — track public flag and type for filtering at output stage
            foreach (var fieldDecl in tds.Members.OfType<FieldDeclarationSyntax>())
            {
                bool isPublicField = fieldDecl.Modifiers.Any(m => m.Text == "public");
                string typeName = fieldDecl.Declaration.Type.ToString().TrimStart('@');
                foreach (var v in fieldDecl.Declaration.Variables)
                    fields.Add(new FieldRef(typeName, v.Identifier.Text.TrimStart('@'), "field", IsPublic: isPublicField));
            }
        }
        else if (typeDecl is EnumDeclarationSyntax enumDecl)
        {
            foreach (var member in enumDecl.Members)
                fields.Add(new FieldRef("", member.Identifier.Text, "value"));
        }

        typeInfos.Add(new TypeInfo(name, ns, kind, bases, methods, fields, isCodegen, filePath));
    }
}

// ---- build a set of project type names for dep filtering ----
var projectTypeNames = new HashSet<string>(typeInfos.Select(t => t.Name));

// ---- emit Mermaid ----
var sb = new StringBuilder();
sb.AppendLine("# Code Map");
sb.AppendLine();
sb.AppendLine("> Auto-generated by `tools/codemap`. Re-run `scripts/generate-codemap.sh` to refresh.");
sb.AppendLine();
sb.AppendLine("```mermaid");
sb.AppendLine("classDiagram");

// Group by namespace for comments
var byNs = typeInfos.GroupBy(t => t.Namespace).OrderBy(g => g.Key);

foreach (var nsGroup in byNs)
{
    sb.AppendLine();
    sb.AppendLine($"    %% namespace: {nsGroup.Key}");

    foreach (var t in nsGroup.OrderBy(x => x.Name))
    {
        string label = t.IsCodegen ? $"{t.Name} [codegen]" : t.Name;

        if (t.Kind == "enum")
        {
            sb.AppendLine($"    class {t.Name} {{");
            sb.AppendLine($"        <<enumeration>>");
            foreach (var v in t.Fields.Where(f => f.Kind == "value"))
                sb.AppendLine($"        {v.Name}");
            sb.AppendLine("    }");
            continue;
        }

        if (t.Kind == "struct")
        {
            sb.AppendLine($"    class {t.Name} {{");
            sb.AppendLine($"        <<struct>>");
            foreach (var f in t.Fields.Where(f => f.Kind == "field" || f.Kind == "property"))
                sb.AppendLine($"        +{f.TypeName} {f.Name}");
            foreach (var m in t.Methods)
                sb.AppendLine($"        +{m.ReturnType} {m.Name}({m.Params})");
            sb.AppendLine("    }");
            continue;
        }

        sb.AppendLine($"    class {t.Name} {{");

        if (t.Kind == "interface")
            sb.AppendLine("        <<interface>>");
        else if (t.IsCodegen)
            sb.AppendLine("        <<codegen>>");

        // Public properties
        foreach (var f in t.Fields.Where(f => f.Kind == "property"))
            sb.AppendLine($"        +{f.TypeName} {f.Name}");

        // Public events
        foreach (var f in t.Fields.Where(f => f.Kind == "event"))
            sb.AppendLine($"        +event {f.TypeName} {f.Name}");

        // Public methods
        foreach (var m in t.Methods)
            sb.AppendLine($"        +{m.ReturnType} {m.Name}({m.Params})");

        // Fields: public primitives always shown; project-type refs shown with correct access modifier
        foreach (var f in t.Fields.Where(f => f.Kind == "field"))
        {
            string bare = StripGeneric(f.TypeName);
            bool isProjectType = projectTypeNames.Contains(bare);
            bool isPrimitive = bare is "float" or "int" or "bool" or "string" or "double"
                               or "Vector2" or "Vector3" or "Vector4" or "Quaternion" or "Color";
            if (!isProjectType && !(f.IsPublic && isPrimitive)) continue;
            string access = f.IsPublic ? "+" : "-";
            sb.AppendLine($"        {access}{f.TypeName} {f.Name}");
        }

        sb.AppendLine("    }");
    }
}

sb.AppendLine();
sb.AppendLine("    %% --- relationships ---");

// Inheritance / implementation
foreach (var t in typeInfos)
{
    foreach (var b in t.Bases)
    {
        string bare = StripGeneric(b).TrimStart('@');
        if (projectTypeNames.Contains(bare))
        {
            var baseInfo = typeInfos.FirstOrDefault(x => x.Name == bare);
            if (baseInfo?.Kind == "interface")
                sb.AppendLine($"    {t.Name} ..|> {bare} : implements");
            else
                sb.AppendLine($"    {bare} <|-- {t.Name} : extends");
        }
    }
}

// Field/property dependencies (only to project types, avoid duplicate lines)
var depLines = new HashSet<string>();
foreach (var t in typeInfos)
{
    foreach (var f in t.Fields.Where(f => f.Kind is "field" or "property"))
    {
        // Check the outer type name and any generic type arguments
        foreach (string bare in ExtractTypeNames(f.TypeName))
        {
            if (projectTypeNames.Contains(bare) && bare != t.Name)
            {
                string line = $"    {t.Name} --> {bare} : {f.Name}";
                if (depLines.Add(line))
                    sb.AppendLine(line);
            }
        }
    }
}

sb.AppendLine("```");

// Write output
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, sb.ToString());
Console.WriteLine($"Written: {outputPath}");
return 0;

// ---- helpers ----

static string GetNamespace(SyntaxNode node)
{
    var ns = node.Ancestors()
        .OfType<BaseNamespaceDeclarationSyntax>()
        .FirstOrDefault();
    return ns?.Name.ToString() ?? "(global)";
}

static string StripGeneric(string typeName)
{
    int idx = typeName.IndexOf('<');
    return idx >= 0 ? typeName[..idx].Trim() : typeName.Trim();
}

// Returns the outer type name plus any generic type arguments (e.g. "List<SplineZone>" -> ["List","SplineZone"])
static IEnumerable<string> ExtractTypeNames(string typeName)
{
    typeName = typeName.Trim();
    int open = typeName.IndexOf('<');
    if (open < 0)
    {
        yield return typeName;
        yield break;
    }
    yield return typeName[..open].Trim();
    string inner = typeName[(open + 1)..typeName.LastIndexOf('>')];
    foreach (string part in inner.Split(','))
        yield return part.Trim().TrimStart('@');
}

// ---- data types ----
record TypeInfo(
    string Name,
    string Namespace,
    string Kind,
    List<string> Bases,
    List<MethodSignature> Methods,
    List<FieldRef> Fields,
    bool IsCodegen,
    string FilePath);

record MethodSignature(string ReturnType, string Name, string Params);
record FieldRef(string TypeName, string Name, string Kind, bool IsPublic = false);
